-- Challenge Update 1.6
-- Выполни этот файл один раз в Supabase SQL Editor.

create table if not exists public.aim_challenge_scores (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 20),
  challenge_date date not null,
  week_start date not null,
  seed integer not null check (seed between 20200101 and 20991231),
  sequence_hash text not null check (char_length(sequence_hash) between 6 and 32),
  score integer not null check (score between 0 and 40),
  accuracy integer not null check (accuracy between 0 and 100),
  reaction integer not null check (reaction between 120 and 9999),
  duration_ms integer not null check (duration_ms between 3000 and 27000),
  created_at timestamptz not null default now()
);

create index if not exists aim_challenge_week_idx
on public.aim_challenge_scores (week_start desc, score desc, reaction asc, accuracy desc);

create index if not exists aim_challenge_day_idx
on public.aim_challenge_scores (challenge_date desc, score desc, reaction asc);

alter table public.aim_challenge_scores enable row level security;

drop policy if exists "Public can read challenge scores" on public.aim_challenge_scores;
create policy "Public can read challenge scores"
on public.aim_challenge_scores for select
to anon, authenticated
using (true);

drop policy if exists "Public can submit challenge scores" on public.aim_challenge_scores;
create policy "Public can submit challenge scores"
on public.aim_challenge_scores for insert
to anon, authenticated
with check (
  char_length(name) between 1 and 20
  and score between 0 and 40
  and accuracy between 0 and 100
  and reaction between 120 and 9999
  and duration_ms between 3000 and 27000
  and seed between 20200101 and 20991231
  and challenge_date = to_date(seed::text, 'YYYYMMDD')
  and week_start <= challenge_date
  and challenge_date < week_start + 7
);

grant select, insert on public.aim_challenge_scores to anon, authenticated;
grant usage, select on sequence public.aim_challenge_scores_id_seq to anon, authenticated;
