create table if not exists public.aim_scores (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 20),
  score integer not null check (score between 0 and 500),
  accuracy integer not null check (accuracy between 0 and 100),
  reaction integer not null check (reaction between 1 and 9999),
  created_at timestamptz not null default now()
);

create index if not exists aim_scores_rating_idx
on public.aim_scores (score desc, reaction asc, accuracy desc);

alter table public.aim_scores enable row level security;

drop policy if exists "Public can read aim scores" on public.aim_scores;
create policy "Public can read aim scores"
on public.aim_scores for select
to anon, authenticated
using (true);

drop policy if exists "Public can submit aim scores" on public.aim_scores;
create policy "Public can submit aim scores"
on public.aim_scores for insert
to anon, authenticated
with check (
  char_length(name) between 1 and 20
  and score between 0 and 500
  and accuracy between 0 and 100
  and reaction between 1 and 9999
);

grant select, insert on public.aim_scores to anon, authenticated;
grant usage, select on sequence public.aim_scores_id_seq to anon, authenticated;
